### PR TITLE
Hide enrollment controls

### PR DESCRIPTION
**Pull request by rshipp**
Hides all 4 places where you can modify enrollment on Canvas (that I found):

1. https://braven.instructure.com/courses/42/users dropdown on individual users
2. https://braven.instructure.com/courses/42/users +PEOPLE button
2. https://braven.instructure.com/users/81
3. https://braven.instructure.com/courses/42/sections/200

Task: https://app.asana.com/0/1174274412967132/1200183754300630/f

I had to dig up the MutationObserver stuff from https://github.com/bebraven/platform/pull/646 for this, since most of this stuff is ajax-loaded. That means we're constantly watching all pages on Canvas for all DOM changes now, and I don't know what the performance cost of that might be.

Before Screenshots:

Screen Shot 2021-05-19 at 1 43 23 PM
Screen Shot 2021-05-19 at 1 45 01 PM
Screen Shot 2021-05-19 at 1 46 27 PM
Screen Shot 2021-05-19 at 1 55 17 PM

After Screenshots:

Screen Shot 2021-05-19 at 1 37 18 PM
Screen Shot 2021-05-19 at 1 37 57 PM
Screen Shot 2021-05-19 at 1 38 35 PM
Screen Shot 2021-05-19 at 1 57 21 PM

### CODE REVIEW

**Comment by sadleb** [comment]
Is there a way to add a query param or some other way to temporarily re-enable for engineers (and maybe QA folks) to use?

**Comment by sadleb** [comment]
> Yes, but why? Is there a reason for someone to mess with things on Canvas? It's already caused issues and wasted troubleshooting time when we "added" people to sections on Canvas but not Platform.

The things I’m thinking:
- if things do get messed up (we release a bug or something), engineers and really savvy product support folks could manually fix it
- Managing test users when working on developing completely new things. E.g. if we started using the Observer role or introduce a custom role. Feels like there may be times we want to be able to do stuff manually when developing things 
- Adding and managing Canvas admin users. Aka staff who we trust with unfettered access.

**Comment by sadleb** [comment]
> > Yes, but why? Is there a reason for someone to mess with things on Canvas? It's already caused issues and wasted troubleshooting time when we "added" people to sections on Canvas but not Platform.
> 
> The things I’m thinking:
> 
> * if things do get messed up (we release a bug or something), engineers and really savvy product support folks could manually fix it
> * Managing test users when working on developing completely new things. E.g. if we started using the Observer role or introduce a custom role. Feels like there may be times we want to be able to do stuff manually when developing things
> * Adding and managing Canvas admin users. Aka staff who we trust with unfettered access.

I’d be cool with a blanket statement that we have to use the API and/or build tools for these use cases though

**Comment by rshipp** [comment]
Well, I was about to just add it until you posted the second comment lol. Are your reasons for adding it enough to justify a secret URL flag that we'll have to maintain and tell people about, or do you not think your reasons are good enough? I don't want to add it, so if you're arguing against yourself that doesn't give me a whole lot of confidence.

**Comment by sadleb** [comment]
Haha, let’s not add it and when we run into a need make a decision at that time what’s better, create a tool or create some API scripts or create a hidden param

**Comment by sadleb** [comment]
Since Honeycomb instrumentation may be too hard here, is it worth adding some console logs when we remove stuff? I’m just picturing 6 mo to a year down the road when we have a valid need for one of those UI options and folks have no clue how or why they are missing. It might provide a clue if there are console logs saying we removed them?

**Review by sadleb — APPROVED** [review]
Lgtm. We might have some short term pain bc of this, but I think it’s worth it long term to force all this to go through platform.

**Pull request merged**
